#!/bin/bash

VERSION=$1
TODAY=$(date "+%Y-%m-%d")

: ${VERSION:?"Need to specify a version e.g. 2.0.1"}

# We have to repeat the version in the Formula file, since it's the only one
# that homebrew loads.
sed -i '' "s/DINGHY_VERSION=.*/DINGHY_VERSION='$VERSION'/g" dinghy.rb
sed -i '' "s/DINGHY_VERSION=.*/DINGHY_VERSION='$VERSION'/g" cli/dinghy/version.rb
sed -i '' $'s/## Unreleased/## Unreleased\
\
## '"$VERSION - $TODAY/g" CHANGELOG.md

if [ "$2" == "frd" ]; then
  git commit -am "v$VERSION"
  git tag "v$VERSION"
  git push origin HEAD:latest
  git push origin "v$VERSION"
fi
