# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

PRIVATE_IP = ENV.fetch("DINGHY_PRIVATE_IP", "192.168.42.10")
RAM = ENV["DINGHY_VM_RAM"]
CPUS = ENV["DINGHY_VM_CPUS"]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define 'dinghy'

  config.vm.box = "codekitchen/boot2docker"

  config.vm.network "private_network", ip: PRIVATE_IP

  config.ssh.shell = "sh"
  config.ssh.username = "docker"

  config.vm.provider :vmware_fusion do |v|
    v.vmx['memsize'] = RAM if RAM
    v.vmx['numvcpus'] = CPUS if CPUS
  end

  config.vm.provider :virtualbox do |v|
    v.customize ['modifyvm', :id, '--memory', RAM] if RAM
    v.customize ['modifyvm', :id, '--cpus', CPUS] if CPUS
  end

  # Forward the Docker TLS port
  config.vm.network :forwarded_port, guest: 2376, host: 2376

  # Disable synced folder by default, we add the full NFS mount below
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Fix busybox/udhcpc issue
  config.vm.provision :shell, run: "always", inline: <<-EOT
    if ! grep -qs ^nameserver /etc/resolv.conf; then
      sudo /sbin/udhcpc
    fi
    cat /etc/resolv.conf
  EOT

  # Adjust datetime after suspend and resume
  config.vm.provision :shell, run: "always", inline: <<-EOT
    sudo /usr/local/bin/ntpclient -s -h pool.ntp.org
    date
  EOT

  # Mount the NFS volume from our own unfs daemon
  config.vm.provision :shell, run: "always" do |s|
    mount_dir = ENV.fetch("HOME")
    s.inline = <<-EOT
      echo Preparing #{mount_dir} NFS mount
      sudo umount #{mount_dir} 2> /dev/null
      sudo mkdir -p #{mount_dir}
      sudo chown docker #{mount_dir}
    EOT
  end
end
