# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Don't make edits to this file, Dinghy will overwrite it on next install.

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

PRIVATE_IP = ENV.fetch("DINGHY_PRIVATE_IP", "192.168.42.10")
RAM = ENV["DINGHY_VM_RAM"]
CPUS = ENV["DINGHY_VM_CPUS"]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define 'dinghy'

  config.vm.box = "codekitchen/boot2docker"
  config.vm.box_version = "1.5.0"

  config.vm.network "private_network", ip: PRIVATE_IP

  config.ssh.shell = "sh"
  config.ssh.username = "docker"
  if config.ssh.respond_to?(:insert_key=)
    config.ssh.insert_key = false
  end

  config.vm.provider :vmware_fusion do |v|
    v.vmx['memsize'] = RAM if RAM
    v.vmx['numvcpus'] = CPUS if CPUS
  end

  config.vm.provider :virtualbox do |v|
    v.customize ['modifyvm', :id, '--memory', RAM] if RAM
    v.customize ['modifyvm', :id, '--cpus', CPUS] if CPUS
    v.customize ['modifyvm', :id, '--natdnsproxy1', 'off']
    v.customize ['modifyvm', :id, '--natdnshostresolver1', 'off']
  end

  # Disable synced folder by default, we add the full NFS mount below
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Fix busybox/udhcpc issue
  # remove the eth1 dhcp daemon, to avoid issues with vmware changing the private network IP address
  config.vm.provision :shell, run: "always", inline: <<-EOT
    sleep 5
    sudo /sbin/udhcpc > /dev/null
    pgrep -lf udhcpc | grep eth1 | cut -f1 -d' ' | sudo xargs kill
    cat /etc/resolv.conf
  EOT

  # Adjust datetime after suspend and resume
  config.vm.provision :shell, run: "always", inline: <<-EOT
    sudo /etc/init.d/services/crond start
    echo '*/5 * * * * /usr/local/bin/ntpclient -s -h pool.ntp.org' | sudo crontab -
  EOT

  # Mount the NFS volume from our own unfs daemon
  config.vm.provision :shell, run: "always" do |s|
    mount_dir = ENV.fetch("HOME")
    s.inline = <<-EOT
      echo Preparing #{mount_dir} NFS mount
      sudo umount #{mount_dir} 2> /dev/null
      sudo mkdir -p #{mount_dir}
      sudo chown docker #{mount_dir}
    EOT
  end
end
